### PR TITLE
Resident detail page calender map

### PR DESCRIPTION
**Pull request by shailee-m**
Adding calendar chart in resident details

### CODE REVIEW

**Comment by brylie** [comment]
Please take the PR out of draft status when you get the chance.

**Comment by shailee-m** [comment]
Depends on this PR. https://github.com/GeriLife/wellbeing-client/pull/12

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
@shailee-m please resolve conflicts when you get the chance

**Review by brylie — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Review by brylie — APPROVED** [review]

**Pull request merged**
