### PR TITLE
Adding activity count chart by homeId

### LINKED ISSUE #588: Add activity counts by facilitator role to Home historic report page
We currently have a dashboard to display historical data for a single home. However, the Home Report dashboard lacks some key charts, such as:

- activity counts by facilitator role

Note: the All Homes report can serve as the reference for this task, since it contains the desired data visualizations.

## Task scope

- [ ] server aggregation function exists
- [ ] server aggregation function uses indexed fields for performance
- [ ] server API endpoint exists
- [ ] Vue client code fetches aggregated data from a server API endpoint
- [ ] Vue client code displays aggregated data in appropriate chart and integrates well with other page elements

### PR DESCRIPTION
**Pull request by shailee-m**
closes https://github.com/GeriLife/wellbeing/issues/588

### CODE REVIEW

**Comment by brylie** [comment]
How quickly does this chart render on a medium-sized data set? Please create one year of mock data with around 1000 activities per home per month and benchmark the chart.

**Comment by shailee-m** [comment]
> How quickly does this chart render on a medium-sized data set? Please create one year of mock data with around 1000 activities per home per month and benchmark the chart.


@brylie 
Screenshot from 2021-08-29 23-36-34

For around 100,000 activities (9 homes; activities of 12 months), the plotly rendering gets slower. (For a single home there should be approximately 12000 data points) for each chart. The APIs respond in under 1 second but with 2 charts on the page and 12000 data points, the plotly rendering slows down.

We could try adding more filters/chart settings in the frontend to restrict the data shown e.g. a date range.  Also, we can look into other libraries that can be faster than plotly. Also, the page hangs a little.

**Comment by brylie** [comment]
There should only be one data point per day/month depending on the aggregation. So, the chart should only render 365 or 12 data points depending on day or month aggregation. 

My main concern is with performance of the server-side aggregation on large data.

**Comment by brylie** [comment]
> For around 100,000 activities (9 homes; activities of 12 months), the plotly rendering gets slower. (For a single home there should be approximately 12000 data points) for each chart. The APIs respond in under 1 second but with 2 charts on the page and 12000 data points, the plotly rendering slows down.

For one home there should be 365 or 12 data points, depending on whether we aggregate by day or month. So, chart performance isn't the concern. 

What I would like to establish is how quickly the _server_ can aggregate the 365 (daily) or 12 (monthly) data points for a single home with a high number (~12,000) of activities.

Notes: the mock data generator will generate data for multiple homes, which is alright. Since the task is to produce an aggregate chart for a single home, we just need to generate enough mock data so there is around 12,000 activities for a single home. Then, benchmark the server performance for a single home daily/monthly activity aggregates over one year.

**Comment by shailee-m** [comment]
> > For around 100,000 activities (9 homes; activities of 12 months), the plotly rendering gets slower. (For a single home there should be approximately 12000 data points) for each chart. The APIs respond in under 1 second but with 2 charts on the page and 12000 data points, the plotly rendering slows down.
> 
> For one home there should be 365 or 12 data points, depending on whether we aggregate by day or month. So, chart performance isn't the concern.
> 
> What I would like to establish is how quickly the _server_ can aggregate the 365 (daily) or 12 (monthly) data points for a single home with a high number (~12,000) of activities.
> 
> Notes: the mock data generator will generate data for multiple homes, which is alright. Since the task is to produce an aggregate chart for a single home, we just need to generate enough mock data so there is around 12,000 activities for a single home. Then, benchmark the server performance for a single home daily/monthly activity aggregates over one year.


Yes, the server responds quickly mostly in ~1.5sec.

**Pull request merged**
