### PR TITLE
Adding hierarchy dropdown for homes.

### LINKED ISSUE #23: Activities Page improvements
Activities page needs some improvements
- Resident select should nest residents by group home (optgroup for each Home)
- localization texts for table column headers

### PR DESCRIPTION
**Pull request by shailee-m**
Closes #23

### CODE REVIEW

**Review by brylie — APPROVED** [review]

**Comment by brylie** [comment]
Looks good. Do you think we can publish this hierarchy dropdown as a Vue/Quasar package?

**Comment by shailee-m** [comment]
> Looks good. Do you think we can publish this hierarchy dropdown as a Vue/Quasar package?

yes, we can. It shouldn't be an issue. we need to expose all slots and events the q-select component exposes, for it to work in various other use cases

**Comment by brylie** [comment]
Very cool. I'll create a repository in the GeriLife namespace. Would you mind creating the hierarchy component? Would it be called `q-select-hierarchy` or perhaps `q-select-groups`?

**Comment by shailee-m** [comment]
q-select-groups seems good

**Comment by brylie** [comment]
Here is the repo: https://github.com/GeriLife/quasar-q-select-group

**Comment by brylie** [comment]
Work incrementally. We might not need to implement the full Quasar component APIs for the initial release.

**Pull request merged**
