### PR TITLE
adding residents list, edit, add

### PR DESCRIPTION
**Pull request by shailee-m**

### CODE REVIEW

**Comment by brylie** [comment]
@shailee-m please resolve conflicts.

**Comment by brylie** [comment]
Clicking "Edit Residency" button opens the "Add Residency" form:

Peek 2020-11-15 18-40

**Comment by brylie** [comment]
Clicking "Add New Residency" opens the "Edit Residency" form:

Peek 2020-11-15 18-42

**Comment by brylie** [comment]
Submitting the "Edit Residency" form throws a server error:

```
Error: Move out is not a valid date in residencies insert
```

**Comment by brylie** [comment]
Please make sure dates are valid in all form submissions for:

- Add residency
  - new resident
  - existing resident
- Edit residency

Try with combinations of 
- both "move in" and "move out" dates
- just "move in" date

All form fields should submit valid dates to the server.

**Review by brylie — CHANGES_REQUESTED** [review]
The wrong forms are showing as mentioned previously. Dates are not passing server validation.

**Comment by shailee-m** [comment]
@brylie the form titles were incorrectly shown. Also, fixed the date issue.

**Pull request merged**
