### PR TITLE
adding residents details page

### PR DESCRIPTION
**Pull request by shailee-m**
All details page features except calendar chart.

### CODE REVIEW

**Comment by brylie** [comment]
I am not able to navigate to the Resident Details Page from either
- Residents page (clicking View Resident button does not work)
- Home details page (clicking resident row in Residents table does not work)

Is this expected?

Peek 2020-12-07 11-40

Peek 2020-12-07 11-41

**Review by brylie — CHANGES_REQUESTED** [review]
I can't test this properly, since the links to the Resident Details page don't seem to work.

**Comment by shailee-m** [comment]
link from the home details page is not added. but the residents page link is working for me. Are you getting any console errors?

**Comment by brylie** [comment]
Ah, yes. It did work. For some reason the branch had not pulled the latest changes from GitHub when I created it via VS Code.

**Review by brylie — CHANGES_REQUESTED** [review]
Make sure to hide the Feelings chart when there is no data.

**Review by brylie — CHANGES_REQUESTED** [review]
Add a "view resident" button with an eye icon on the Home Details Residents table.

**Comment by shailee-m** [comment]
> Add a "view resident" button with an eye icon on the Home Details Residents table.

done

**Pull request merged**
