### PR TITLE
34 avoiding reload in submit button

### LINKED ISSUE #34: Submitting login form refreshes page in static build
When deploying to the Dokku server, we use a static build plugin. For some reason, the login form doesn't handle the submit event correctly in the static build and refreshes the page. When inspecting the form listeners, it doesn't seem like the Vue submit handler is being called.

Testing deployment:
http://95.217.223.95/#/login

Determine how to build the static version of this client app so that forms work correctly. As a start, make sure the login page works in a static build (and test the Dokku deployment).

### PR DESCRIPTION
**Pull request by shailee-m**
closes #34 

This should avoid the page reload on login failure.
Adding prevent default at places we use q-form submit

### CODE REVIEW

**Comment by shailee-m** [comment]
@brylie Can I get a valid login cred to check if the reloading issue is happening for other forms as well?

**Comment by brylie** [comment]
@shailee-m I will set up a login for you today.

Make sure to try using the Vue `.prevent` event modifier, since it is designed for this purpose:
https://v3.vuejs.org/guide/events.html#event-modifiers

**Comment by brylie** [comment]
User: test@user.com
PW: test123

**Comment by shailee-m** [comment]
@brylie the event modifier is there in the login form. Does not seem to work. Also, in the local build, it does not reload the page back to login URL. So I think we should deploy this and try

**Comment by brylie** [comment]
You can deploy this branch using the command `git push dokku 34-login-reload:main` Dokku will deploy an app from the `main` branch, but the previous command pushes the `34-login-reload` branch to `main` on the `dokku` remote.

**Comment by brylie** [comment]
This branch doesn't fix the error in the deployed version. I am starting to wonder whether `axios` may be failing to make the request and causing the page to reload. I am encountering a similar issue when running the project locally in development mode.

**Comment by brylie** [comment]
I think the issue is with the following code:

```
if (await loginToServer(this.email, this.password)) {
        console.log("logged in to server");

        await this.$store.dispatch("user/getUserDetails");
        await this.$store.dispatch("user/getGroupsOfCurrentUser");

        window.location.reload();
        window.location.href = "/#/";
      } else {
        console.log("Could not log in to server.");
      }
```

Specifically, the `window.location.reload()` should be unnecessary. Let's refer to the Vue guide for a more conventional pattern to managing authentication in Vue apps.


https://www.smashingmagazine.com/2020/10/authentication-in-vue-js/

**Pull request closed without merging**
